onlineshop/customer/api/urls.py
from django.urls import path

from customer.api import views

urlpatterns = [
    path('', views.customerlist, name='customerlist'),
    path('register/', views.register, name='register'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
]

onlineshop/customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('logout/', views.auth_logout, name='logout'),
]

onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls', 'product')),
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls')),
    path('customer/', include('customer.urls', 'customer')),
    path('order/', include('order.urls', 'order'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('single_product/', views.single_product, name='single_product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('checkout/', views.checkout, name='checkout')
]

onlineshop/product/urls.py
from django.urls import path

from product import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'),
]

onlineshop/customer/models.py
from django.db import models
from django.contrib.auth.models import User

from phonenumber_field.modelfields import PhoneNumberField
from account.models import Account


class Customer(User):
    phone = PhoneNumberField(null=True, blank=True)
    address = models.TextField(max_length=400, null=True, blank=True)

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.username}"


class Coupon(models.Model):
    code = models.CharField(max_length=20)
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE, related_name='coupon')
    expire_date = models.DateTimeField()

    def __str__(self):
        return f"{self.customer}'s coupon"


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='customer')

onlineshop/customer/forms.py
from phonenumber_field.formfields import PhoneNumberField
from django import forms
from customer.models import Customer


class EditProfileForm(forms.ModelForm):
    phone = PhoneNumberField(required=False)
    address = forms.Textarea()

    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'username', ]

onlineshop/customer/api/views.py
from django.http import HttpResponse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.shortcuts import get_list_or_404, render, redirect
from django.core.mail import send_mail
from django.contrib import messages

from customer.api.serializer import *


def create_customer_property_func(req):
    customer = Customer.objects.create(
        username=req.POST['username'],
        email=req.POST['email'],
        phone=req.POST['phone'],
    )
    customer.save()
    customer.set_password(req.POST['password'])
    customer.save()


@api_view(['GET', 'POST'])
def register(request):
    if request.method == 'POST':
        # print(request.POST)
        res = dict()
        if not len(request.POST['password']) > 8:
            if request.POST['password'] == request.POST['password2']:
                res['success'] = True
                res['link'] = '/customer/login'
                create_customer_property_func(request)
            else:
                res['success'] = False
        else:
            res['success'] = False
        return Response(res)


@api_view(['GET', 'POST'])
def customerlist(request):
    if request.method == 'GET':
        customer = get_list_or_404(Customer)
        serializer = CustomerSerializer(customer, many=True, context={'request': request})
        return Response(serializer.data)

    elif request.method == 'POST':
        customer = CustomerSerializer(data=request.data)
        if customer.is_valid():
            customer_instance = customer.save()
            customer_instance.set_password(customer.validated_data['password'])
            customer_instance.save()


@api_view(['GET', 'POST'])
def forgetpassword(request):
    if request.method == 'POST':
        res = dict()
        username = request.POST['username']
        try:
            customer = Customer.objects.get(username=username)
            if customer:
                his_email = customer.email
                new_password = Customer.objects.make_random_password(length=20)
                res['success'] = True
                res['link'] = '/customer/login'
                res['msg'] = f'Your new password sent to {his_email}. Please login with this'
                messages.success(request, res['msg'])
                customer.set_password(new_password)
                customer.save()
                send_mail('your new password',
                          f'your reset password is {new_password}',
                          'security@onlineshop.com',
                          [his_email],
                          fail_silently=False, )
            else:
                res['success'] = False
                res['link'] = 'customer/forgetpassword'
                res['msg'] = 'This username is not exist!'
                messages.error(request, res['msg'])
                return Response(res, status=status.HTTP_400_BAD_REQUEST)

        except:
            res['success'] = False
            res['link'] = 'customer/forgetpassword'
            res['msg'] = 'Something went wrong'
            messages.error(request, res['msg'])
            return Response(res, status=status.HTTP_400_BAD_REQUEST)

        return Response(res)
    return redirect('customer:forgetpassword')

onlineshop/customer/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from customer.forms import EditProfileForm
from customer.models import Customer
from product.models import Product


# just render the related page
def login(request):
    return render(request, 'customer/login.html', {'request': request})


# just render the related page
def signup(request):
    return render(request, 'customer/signup.html', {'request': request})


# just render the related page
def forgetpassword(request):
    return render(request, 'customer/forget_password.html', {'request': request})


@login_required
def profile(request):
    if request.method == 'GET':
        this_user = Customer.objects.get(id=request.user.id)
        phone = this_user.phone
        address = this_user.address
        # print(this_user, phone, address)
        return render(request, 'customer/profile.html', {
            'request': request,
            'phone': phone,
            'address': address,
        })
    if request.method == 'POST':
        pass


@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('customer:profile')
    else:
        form = EditProfileForm(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'customer/profile_edit.html', context)


def auth_logout(request):
    logout(request)
    return render(request, 'product/home.html', {'request': request})

onlineshop/customer/templates/customer/forget_password.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    forget | Onlineshop
{% endblock %}

{% block style %}
    <style>
        #card-body {
            background-color: rgba(139, 156, 123, 0.44);
        }

        #button {
            background-color: rgba(106, 201, 17, 0.87);
        }
    </style>
{% endblock %}

{% block extra_header %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5" id="card-body">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>enter your username</b></h5>

                        <form id="form">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='username' id="username" required>
                                <label for="username">Username</label>
                            </div>

                            <button class="btn btn-primary btn-login" id="button" type="button">
                                sent email
                            </button>

                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static "customer/js/forget_password.js" %}"></script>
{% endblock %}

onlineshop/customer/templates/customer/login.html
{% extends 'product/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'customer/css/login.css' %}">
{% endblock %}

{% block title %}
    Login | Onlineshop
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5" id="card-body">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Login</b></h5>

                        <form action="{% url 'product:home' %}" method="post">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='username' id="username" required>
                                <label for="username">Username</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" name="password" id="password"
                                       placeholder="Password" required>
                                <label for="password">Password</label>
                            </div>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div>
                                <a href="{% url "customer:forgetpassword" %}">forgot password?</a>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit"
                                        id="submit">
                                    log in
                                </button>
                            </div>
                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

onlineshop/customer/templates/customer/orderhistory.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
Your History | Onlineshop
{% endblock %}

onlineshop/customer/templates/customer/profile.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    Profile | Onlineshop
{% endblock %}

{% block style %}
    <style>
        #button {
            background-color: rgba(106, 201, 17, 0.87);
        }
    </style>
{% endblock %}

{% block left_items_in_nav %}
    <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
{% endblock %}

{% block right_items_in_nav %}
    <a href={% url 'order:add_to_cart' %}>
        <span class="cart-nav">
            <img src="{% static 'product/img/cart.jpg' %}" style="max-height: 2.5rem" alt="cart-icon">
        </span>
    </a>
{% endblock %}

{% block main %}
    {% if request.user.is_authenticated %}
        <div class="card col-12" style="margin-top: 10px;">
            <div class="card-body">
                <p class="card-text">username: {{ request.user.username }}</p>
                {% if not request.user.first_name %}
                    <p class="card-text">first name: Not set</p>
                {% else %}
                    <p class="card-text">first name: {{ request.user.first_name }}</p>
                {% endif %}
                {% if not request.user.last_name %}
                    <p class="card-text">last name: Not set</p>
                {% else %}
                    <p class="card-text">last name: {{ request.user.last_name }}</p>
                {% endif %}
                {% if not address %}
                    <p class="card-text">address: Not set</p>
                {% else %}
                    <p class="card-text">address: {{ address }}</p>
                {% endif %}
                <p class="card-text">email: {{ request.user.email }}</p>
                <p class="card-text">phone: {{ phone }}</p>
            </div>
        </div>
        <div class="col-1">
            <a class="btn" id="button" href="{% url "customer:profile_edit" %}">edit</a>
        </div>
    {% endif %}

{% endblock %}

onlineshop/customer/templates/customer/profile_edit.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    Profile | Onlineshop
{% endblock %}

{% block style %}
    <style>
        #button {
            background-color: rgba(106, 201, 17, 0.87);
        }
    </style>
{% endblock %}

{% block left_items_in_nav %}
    <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-12" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5" id="card-body">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>edit your profile</b></h5>
                        <div class="form-group">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button class="btn btn-primary btn-login text-uppercase fw-bold" id="button"
                                        type="submit">
                                    Update
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

onlineshop/customer/templates/customer/signup.html
{% extends 'product/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'customer/css/signup.css' %}">
{% endblock %}

{% block title %}
Signup | Onlineshop
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5" id="card-body">
                    <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Sign up</b></h5>
                    <form id="form">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="username" id="username"
                                   placeholder="Username" required>

                            <label for="username">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" name="email" id="email" placeholder="email">

                            <label for="email">Email</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="phone" id="phone" placeholder="phone">

                            <label for="phone">Phone</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name="password" id="password"
                                   placeholder="Password" required>
                            <label for="password">Password</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name="password2" id="password2"
                                   placeholder="Password Confirmation" required>
                            <label for="password2">Password Confirmation</label>
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold" id="button" type="button">
                                Sign Up
                            </button>
                        </div>
                        <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'customer/js/register.js' %}"></script>
{% endblock %}