onlineshop/customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('logout/', views.auth_logout, name='logout'),
]

onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls', 'product')),
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls')),
    path('customer/', include('customer.urls', 'customer')),
    path('order/', include('order.urls', 'order'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/order/api/urls.py
from django.urls import path

from order.api import views

urlpatterns = [
    path(
        '',
        views.OrderViewSet.as_view({'get': 'orderlist'}),
        name='orderlist'),

    path(
        'orderspruduct/<int:pk>',
        views.OrderViewSet.as_view({'get': 'product'}),
        name='orders_product'),

    path(
        'orderscustomer/<int:pk>',
        views.OrderViewSet.as_view({'get': 'customer'}),
        name='orders_customer'
    ),
]

onlineshop/order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('single_product/', views.single_product, name='single_product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('checkout/', views.checkout, name='checkout')
]

onlineshop/order/models.py
from django.db import models
from customer.models import Customer
from product.models import Product


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order_item = models.ManyToManyField(OrderItem)
    total_price = models.PositiveIntegerField(default=0)

    AVAILABLE = 'AVAILABLE'
    UNAVAILABLE = 'UNAVAILABLE'
    availability_choices = (
        (AVAILABLE, 'AVAILABLE'),
        (UNAVAILABLE, 'UNAVAILABLE')
    )
    availability = models.CharField(choices=availability_choices, max_length=100, default=AVAILABLE)

    def __str__(self):
        return str(self.id)

onlineshop/order/api/views.py
from rest_framework import viewsets
from rest_framework.response import Response
from django.shortcuts import get_list_or_404

from customer.models import Customer
from order.api.serializer import OrderslistSerializer
from order.models import Order
from product.models import Product


class OrderViewSet(viewsets.ViewSet):
    def orderlist(self, request):
        queryset = get_list_or_404(Order)
        serializer = OrderslistSerializer(queryset, many=True, context={'request': request})
        return Response(serializer.data)

    def product(self, request, pk):
        queryset = get_list_or_404(Product, id=pk)
        serializer = OrderslistSerializer(queryset, many=True, context={'request': request})
        return Response(serializer.data)

    def customer(self, request, pk):
        queryset = get_list_or_404(Customer, id=pk)
        serializer = OrderslistSerializer(queryset, many=True, context={'request': request})
        return Response(serializer.data)

onlineshop/order/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

from customer.models import Customer
from order.models import Order, OrderItem
from product.models import Product


def cart(request):
    if request.session.get('cart'):
        the_cart = request.session.get('cart')
        total = 0
        product_list = dict()

        for i in the_cart:
            product = Product.objects.filter(id=i).first()
            product_list[product] = the_cart[i]
            total += product.initial_price * int(the_cart[i])

        context = {
            'products': product_list,
            'total': total,
        }
        return render(request, 'order/cart.html', context)

    return render(request, 'order/cart.html', {'request': request})


@csrf_exempt
def single_product(request):
    if request.method == 'POST':
        product_id = request.POST['id']
        selected_product = get_object_or_404(Product, id=product_id)
        return render(request, 'product/single_product.html', {'request': request, 'product': selected_product})
    return render(request, 'product/single_product.html', {'request': request})


@csrf_exempt
def add_to_cart(request):
    if request.method == 'POST':
        product_id = request.POST['product_id']
        qty = request.POST['qty']
        if not request.session.get('cart'):
            request.session['cart'] = {
                product_id: qty
            }
        else:
            the_cart = request.session.get('cart')
            the_cart[product_id] = qty
            request.session.modified = True

        print(request.session.get('cart'))
        return redirect("order:cart")


def delete_from_cart(request, product_id):
    the_cart = request.session.get('cart')
    the_cart.pop(str(product_id))
    request.session.modified = True
    return redirect("order:cart")


def checkout(request):
    if request.user.is_authenticated:
        order_item_list = list()
        total_price = 0
        the_cart = request.session.get('cart')  # {product_id: quantity, ...}

        if the_cart:
            for product_id in the_cart:
                selected_product = Product.objects.filter(pk=product_id).first()  # number of existing product in shop
                quantity = the_cart[product_id]  # number of product that user wants to buy

                if selected_product.stock >= int(quantity):
                    Product.objects.filter(pk=product_id).update(stock=selected_product.stock - int(quantity))

                order_item = OrderItem.objects.create(product=selected_product, quantity=quantity)
                order_item_list.append(order_item)
                total_price += selected_product.generate_final_price * int(quantity)  # calculate total price

            customer = Customer.objects.get(id=request.user.id)
            print(customer)
            order = Order.objects.create(
                customer=customer,
                total_price=total_price,
            )

            order.order_item.add(*order_item_list)
            request.session.pop('cart')

            messages.success(request, 'Your order Recorded successfully')
            return render(request, "order/checkout_done.html", {'request': request})

        else:
            messages.error(request, "you don't have any orders yet!")
            return render(request, "order/checkout_done.html", {'request': request})

    else:
        return render(request, "customer/login.html", {'request': request})

onlineshop/order/templates/order/cart.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    Cart | Onlineshop
{% endblock %}

{% block left_items_in_nav %}
    {% if not request.user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'customer:signup' %}">Signup</a>
        <a class="btn btn-success" href="{% url 'customer:login' %}">Login</a>
    {% else %}
        <a class="btn btn-success" href="{% url 'customer:profile' %}">Profile</a>
        <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
    {% endif %}
{% endblock %}

{% block main %}
    <div class="card-body col-12" style="margin-top: 10px">
        <table class="table table-secondary">
            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">name</th>
                <th scope="col">stock</th>
                <th scope="col">price</th>
                <th scope="col">quantity</th>
            </tr>
            </thead>
            {% for product, qty in products.items %}
                <tbody>
                <tr>
                    <th scope="row"><img src="/media/{{ product.photo }}" alt="{{ product.photo }}"
                                         style="max-height: 150px"></th>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.stock }}</td>
                    <td id="price"
                        value="{% widthratio qty 1 product.initial_price %}">{% widthratio qty 1 product.initial_price %}</td>
                    <td id="qty" value="{{ qty }}">
                        {{ qty }}
                        <a class="btn btn-danger" href="{% url 'order:delete_from_cart' product.id %}">remove</a>
                    </td>

                </tr>
                </tbody>
            {% endfor %}
        </table>
        <div class="container row">
            <div class="col-2 ckeckout-btn">
                {% if request.user.is_authenticated %}
                    <a class="btn btn-success" href="{% url 'order:checkout' %}">checkout</a>
                {% else %}
                    <a class="btn btn-success" href="{% url 'customer:login' %}">checkout</a>
                {% endif %}
            </div>
            <div class="col-8">

            </div>
            <div class="col-2">
                <span class="span" style="background-color: rgb(175,89,89); padding: 10px">total: {{ total }}</span>
            </div>
        </div>
    </div>
{% endblock %}

onlineshop/order/templates/order/checkout_done.html
{% extends 'product/base.html' %}

{% block title %}DONE! | OnlineShop{% endblock %}

{% block main %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endblock %}