onlineshop/customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('logout/', views.auth_logout, name='logout'),
]

onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls', 'product')),
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls')),
    path('customer/', include('customer.urls', 'customer')),
    path('order/', include('order.urls', 'order'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('single_product/', views.single_product, name='single_product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('checkout/', views.checkout, name='checkout')
]

onlineshop/product/api/urls.py
from django.urls import path

from product.api import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductAPIView.as_view()),
    path('<str:category>/', views.ProductAPIView.as_view()),
    path('categories/', views.CategoryAPIView.as_view(), name='categories'),
]

onlineshop/product/urls.py
from django.urls import path

from product import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'),
]

onlineshop/product/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    parent_category = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.category_name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=80)
    dyn_attr = models.JSONField(null=True, blank=True)
    percent = models.PositiveIntegerField(default=0, blank=True)
    initial_price = models.PositiveIntegerField(default=0, blank=True)
    stock = models.SmallIntegerField(default=0)
    description = models.TextField()
    photo = models.ImageField(upload_to='product_image', null=True, blank=True)

    def __str__(self):
        return self.product_name

    @property
    def generate_final_price(self):
        """
        final_price = Result of initial price deduction from discount percent
        """
        final_price = self.initial_price - (self.initial_price * (self.percent / 100))
        return final_price

onlineshop/product/api/views.py
from django.shortcuts import get_list_or_404, get_object_or_404
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from product.api.serializer import ProductsListSerializer, CategoryListSerializer
from product.models import Product, Category


class ProductAPIView(APIView):
    serializer = ProductsListSerializer

    def get_queryset(self):
        return Product.objects.all()

    def get(self, request, category=None):
        if category:
            queryset = get_list_or_404(Product, category__category_name=category)
        else:
            queryset = self.get_queryset()

        serializer = ProductsListSerializer(queryset, context={'request': request}, many=True)
        return Response(serializer.data)


class CategoryAPIView(APIView):
    def get(self, request):
        print('resid be view')
        queryset = Category.objects.all()
        serializer = CategoryListSerializer(queryset, context={'request': request}, many=True)
        return Response(serializer.data)

onlineshop/product/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_list_or_404
from django.contrib import messages

from product.models import Category, Product


def home(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return render(request, 'product/home.html', {'request': request})
        else:
            message = 'username or password is not correct!'
            messages.error(request, message)
            return redirect('customer:login')

    return render(request, 'product/home.html', {'request': request})

onlineshop/product/templates/product/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static '/product/css/base.css' %}">

    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="main-container">
    <div class="header">

        <nav class="navbar navbar-fixed-top">

            <div class="left_items_in_nav">
                <div class="container">
                    <a href="{% url 'product:home' %}" type="button" class="btn navs-button btn-success">Home</a>
                    {% block left_items_in_nav %}{% endblock %}
                </div>
            </div>

            <div class="right-items-in-nav">
                <div class="container">
                    {% block right_items_in_nav %}{% endblock %}
                </div>
            </div>
        </nav>
        {% block extra_header %}{% endblock %}
    </div>

    <div class="container outer-main">
        <div class="row main-component">
            {% block main %}{% endblock %}
        </div>
    </div>

    <div class="container-fluid footer" id="footer">
        <p>This is footer</p>
        {% block extra_footer %}{% endblock %}
    </div>
</div>

{% block js %}{% endblock %}
</body>
</html>

onlineshop/product/templates/product/home.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}HOME | OnlineShop{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static '/product/css/home.css' %}">
{% endblock %}

{% block left_items_in_nav %}
    {% if not request.user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'customer:signup' %}">Signup</a>
        <a class="btn btn-success" href="{% url 'customer:login' %}">Login</a>
    {% else %}
        <a class="btn btn-success" href="{% url 'customer:profile' %}">Profile</a>
        <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
    {% endif %}
{% endblock %}

{% block right_items_in_nav %}
    <a href={% url 'order:cart' %}>
        <span class="cart-nav">
            <img src="{% static 'product/img/cart.jpg' %}" style="max-height: 2.5rem" alt="cart-icon">
        </span>
    </a>
    <div class="search-bar">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success my-2 my-sm-0" type="submit" id="search-btn">Search</button>
    </div>
{% endblock %}

{% block extra_header %}
    <section class="section category">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Categories: </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto"></ul>
            </div>
        </nav>
    </section>
{% endblock %}

{% block main %}
    <section>
        <div class="container product-container">
            <div class="card-group">
                <div class="row"></div>
            </div>
        </div>
    </section>
{% endblock %}

{#{% block main_right %}#}
{#    <div class="container right-component">#}
{##}
{#    </div>#}
{#{% endblock %}#}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'product/js/categories_nav.js' %}"></script>
    <script src={% static 'product/js/products.js' %}></script>
{% endblock %}

onlineshop/product/templates/product/single_product.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    product | Onlineshop
{% endblock %}

{% block left_items_in_nav %}
    {% if not request.user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'customer:signup' %}">Signup</a>
        <a class="btn btn-success" href="{% url 'customer:login' %}">Login</a>
    {% else %}
        <a class="btn btn-success" href="{% url 'customer:profile' %}">Profile</a>
        <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
    {% endif %}
{% endblock %}

{% block main %}
    <div class="card-body col-12" style="margin-top: 10px">
        <form method="POST" action="{% url 'order:add_to_cart' %}">

            <table class="table table-secondary">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">name</th>
                    <th scope="col">stock</th>
                    <th scope="col">price</th>
                    <th scope="col">quantity</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row"><img src="/media/{{ product.photo }}" alt="{{ product.photo }}"
                                         style="max-height: 150px"></th>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.stock }}</td>

                    <td id="price" value="{{ product.initial_price }}">{{ product.initial_price }}</td>
                    <td>
                        <input oninput="CalculatePrice()" name="qty" id="qty" type="number" value="1">
                    </td>
                </tr>
                </tbody>

            </table>
            <div class="col-2">
                <input type="hidden" name="product_id" value={{ product.id }}>
                <button type="submit" class="btn btn-success">add to cart</button>
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        function CalculatePrice() {
            console.log({{ product.initial_price }})
            let qty = $('#qty').val()
            if (qty > {{ product.stock }}) {
                alert('This amount is more than inventory!')
                qty = 1
            }
            let total = qty * {{ product.initial_price }}
                $('#price').empty().append(total)
        }

    </script>
{% endblock %}